// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForSkyRentalAppFCM12345',
    appId: '1:100000000000:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '100000000000',
    projectId: 'skyrental-admin',
    authDomain: 'skyrental-admin.firebaseapp.com',
    storageBucket: 'skyrental-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOZcHGydKqaWJm_95qHlYj4S8nZc9myQ',
    appId: '1:516557052175:android:9487c4ae010699fcc3c67a',
    messagingSenderId: '516557052175',
    projectId: 'sky-push-notification-b7c72',
    storageBucket: 'sky-push-notification-b7c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForSkyRentalAppFCM12345',
    appId: '1:100000000000:ios:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '100000000000',
    projectId: 'skyrental-admin',
    storageBucket: 'skyrental-admin.appspot.com',
    iosBundleId: 'com.example.skyrentalAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForSkyRentalAppFCM12345',
    appId: '1:100000000000:ios:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '100000000000',
    projectId: 'skyrental-admin',
    storageBucket: 'skyrental-admin.appspot.com',
    iosBundleId: 'com.example.skyrentalAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForSkyRentalAppFCM12345',
    appId: '1:100000000000:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '100000000000',
    projectId: 'skyrental-admin',
    authDomain: 'skyrental-admin.firebaseapp.com',
    storageBucket: 'skyrental-admin.appspot.com',
  );
}
